### ISSUE TITLE
字体显示问题

### ISSUE THREAD

**Issue by Stevesuk0** [MXYLR/Black-Mesa-workshop-mods-CN-Translation-project#1]
嗯 22年我做过bms bshift流程带中文字幕 其实我确实试了试这个这个汉化补丁 但是字体问题啥的不好说 总感觉有些字有点突兀

所以是否可以尝试使用**更换字体**方式来提高显示效果？

**Comment by MXYLR** [comment]
可以, 我也有这个想法, 但是目前这个模组还在一直更新, 所以我想等他们把模组所有关卡都做完了之后, 再单独发一个修改了字体的补丁

**Comment by MXYLR** [comment]
这个字体的问题我自己玩的时候也非常难受, 但是目前的计划是以官方那边为主, 等他们把所有东西做完了再解决其它的细节问题
